/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "urjiqlzbxsbgonbqhoty"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyamlxbHpieHNiZ29uYnFob3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxNzI5NjYsImV4cCI6MjA4Mzc0ODk2Nn0.l5T_Heezih6VcQkBcTEEl8-0brI_a-KPeHKmaqOM_kg"